name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" >> ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem
        sudo apt-get install -y sshpass

    - name: Deploy to EC2
      run: |
        rsync -avz -e "ssh -i ec2_ssh_key.pem -o StrictHostKeyChecking=no" --exclude '.git*' ./ ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_SSH_HOST }}:/var/www/online.esic.edu 

